# Site settings
title: Chris Rees
description: Portfolio
url: "https://chrisrees.dev"
baseurl: ''

# User settings
author:
  name: Chris Rees
  description: I'm a Software Developer, always searching for the next challenge; no task is too scary nor too difficult.
  title: Senior Software Developer
  contact:
    email: i.am@chrisrees.dev
    github_username: serneum
    linkedin_username: serneum

exclude: ['package.json', 'src' , 'node_modules']
