version: '3.4'

services:
  jekyll:
    environment:
      - JEKYLL_ENV=docker
    ports:
      - 9100:4000
    networks:
      - caddy
    labels:
      caddy: chrisrees.dev
      caddy.reverse_proxy: "{{upstreams 4000}}"
      caddy.import: "cloudflare-tls"

networks:
  caddy:
    external:
      name: caddy_default
